#!/usr/bin/env python3
#
# Run checks against HPE Aruba Networking Central
#
#
# Version 0.2
#
import os, sys
import argparse
import pprint
import pickle
import requests
import logging
import time
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
from lib.generic_plugin import *

# parse command line parameters
cli = argparse.ArgumentParser \
    (description='Maintain Aruba Central token')

cli.add_argument('--id',
        help='Client Id',required = True)
cli.add_argument('--secret',
        help='Client Secret', required = True)
cli.add_argument('--token',
		help='initial refresh token', required = True)
cli.add_argument('--baseurl',
		help='base URL for our acocunt', required = False)
cli.add_argument('--dbdir',
		help='directory where keys are stored', required = False)
cli.add_argument('--minttl', type=int,
		help='minimum TTL for token before it is renewed', required = False)
cli.add_argument('-d', '--debug', 
        help='enable debugging output', action="store_true")
args = cli.parse_args()

#### init vars
# check output
rcode=0
out_text=''
detail=''
perfdata=''

# arguments / settings
baseURL     = args.baseurl or 'https://apigw-eucentral2.central.arubanetworks.com'
dbDir       = args.dbdir or '/var/spool/icinga2/tmp'
minttl      = args.minttl or 1800 #( 30mins )
# Strip trailing /
dbDir.rstrip('/')
clientId     = args.id
clientSecret = args.secret
refreshToken = args.token
DEBUG        = args.debug
if DEBUG: pp = pprint.PrettyPrinter(indent=4, compact=True, sort_dicts=True)

#-----------------------------------------------------------------------
# Functions
#-----------------------------------------------------------------------

# Handle API Request
def apiRequest( url, method ):
    result = None

    if method == 'post':
        resp = requests.post( url )
    else:
        resp = requests.get( url )

    if resp:
        result = resp.json()
    else:
        logging.error("something went wrong\n\nRESP_HEADER\n{}\nRESP_TEXT\n{}".format( \
                resp.headers, resp.text ))
    return(result)
# Refresh Token
def renewToken( baseURL, clientId, clientSecret, refreshToken):

    url="{}/oauth2/token?client_id={}&client_secret={}&grant_type=refresh_token&refresh_token={}".format(baseURL, clientId, clientSecret, refreshToken)

    jdata=apiRequest( url, 'post' )

    if not jdata:
        print('Could not get data, aborting')
        sys.exit(1)

    tokenData = { 
            'access' : jdata.get('access_token'),
            'refresh' : jdata.get('refresh_token'),
            'expires' : jdata.get('expires_in')
     }
    return tokenData

# Write token file
def writeFile(fpath, data):
    try:
        tokenCache = open(fpath, 'wb')
    except PermissionError as error:
        print('Pls. check directory permissions!', error)
        sys.exit(11)
    except:
        print ('something failed (exeption while writing file)')
        sys.exit(11)
    else:
        pickle.dump(data, tokenCache)
        tokenCache.close()

def refreshTokenFile (dbDir, baseURL,
                  clientId, clientSecret, refreshToken ):
    # Checking write access
    if not os.access(dbDir, os.W_OK):
        print('UNKNOWN: error: can not write to dbdir')
        sys.exit(3)

    tokenFilePath = dbDir + '/' + clientId + '.token'

    # get new token
    tokenData = renewToken( baseURL, clientId, clientSecret, refreshToken )
    # add current timestamp
    tokenData['file_created'] = int(time.time())

    if DEBUG:
        print('new token data is:')
        pp.pprint( tokenData )
        print('------------------')
    writeFile( tokenFilePath, tokenData )
    return True


#-----------------------------------------------------------------------
#                                 MAIN
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# try to read file
tokenFilePath = dbDir + '/' + clientId + '.token'
try:
    tokenCache = open(tokenFilePath, 'rb')

except FileNotFoundError:
    refreshTokenFile( dbDir, baseURL, clientId, clientSecret, refreshToken )
except PermissionError as e:
    print('internal error: no permission to access DB file')
except:
    print('exception while opening file for reading')

else:
    try:
        if DEBUG: print('pickle load')
        filedata = pickle.load(tokenCache)
    except:
        print('exception while reading file contents')
        # issue an UNKNOWN here, suggest to delete the file
    else:
        print('calculate expiration time')
        expire_time = filedata['file_created'] + filedata['expires']
        ttl = expire_time - int(time.time())
        if DEBUG:
            print('reading data finished!')
            pp.pprint( filedata )
        if ttl > minttl:
            out_text = 'Token valid, expires in {} seconds'.format( ttl )
        else:
            refresh_try = refreshTokenFile(
                    dbDir, baseURL, clientId, clientSecret, refreshToken )
            if refresh_try:
                rcode=0
                out_text='Successfully renewed token'
            else:
                rcode=1
                out_text='Problem while renewing token'

#Finally, print check output and exit with rcode
if not perfdata:
    print("{} {}".format( rcstring(rcode), out_text ))
else:
    print("{} {}|{}".format( rcstring(rcode), out_text, perfdata ))

sys.exit(rcode)

# vim: ts=4:expandtab:sw=4:sts=4:ai:smartindent:filetype=python

