#!/usr/bin/env python3
#
# Run checks against HPE Aruba Networking Central
#
#
# Version 0.1
#
import os, sys
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
import argparse
import pprint
import pickle
from datetime import *
from lib.jsonapi import *
from lib.generic_plugin import *

# parse command line parameters

cli = argparse.ArgumentParser \
    (description='Maintain Aruba Central token')

cli.add_argument('--id', help='Client Id', required = True)
cli.add_argument('--secret', help='Client Secret', required = True)
cli.add_argument('--refresh-token', help='initial refresh token', required = False)
cli.add_argument('--baseurl', help='base URL for our acocunt', required = False)
cli.add_argument('--dbdir', help='directory where keys are stored', required = False)
cli.add_argument('-d', '--debug', help='enable debugging output', action="store_true")
args = cli.parse_args()

#### init vars
# check output
rcode=0
out_text=''
detail=''
perfdata=''

# arguments / settings
baseURL      = args.baseurl or 'https://apigw-eucentral2.central.arubanetworks.com'
dbDir        = args.dbdir or '/var/spool/icinga2/tmp'
# Strip trailing /
dbDir.rstrip('/')
clientId     = args.id
clientSecret = args.secret
DEBUG        = args.debug
if DEBUG: pp = pprint.PrettyPrinter(indent=4, compact=True, sort_dicts=True)

# functions
def refreshToken( baseURL, clientId, clientSecret, refreshToken):
    url="{}/oauth2/token?client_id={}&client_secret={}&grant_type=refresh_token&refresh_token={}".format(baseURL, clientId, clientSecret, refreshToken)
    jdata=request_json( url )

def writeFile(fpath, data):
    try:
        tokenCache = open(fpath, 'wb')
    except PermissionError as error:
        print('Pls. check directory permissions!', error)
    except:
        print ('something failed (exeption while writing file)')
    else:
        print( 'file opened!!' )
        pickle.dump(data, tokenCache)
        tokenCache.close()

    print("printing this to {}:".format( fpath ))
    pp.pprint(data)


#-----------------------------------------------------------------------
#                                 MAIN
#-----------------------------------------------------------------------

# ------------------ Doc ----------------
# Fileformat:
# <type>;<create timestamp>;<value>
# where type can be access, refresh

tokenFilePath = dbDir + '/' + clientId + '.token'

# dummy data
testdata = {
        'access': {
            'created': 123456787,
            'value': 'accessasdfasdfasdf'
            },
        'refresh': {
            'created': 123456789,
            'value': 'accessasdfasdfasdf'
            }
        }
# /dummy data

try:
    tokenCache = open(tokenFilePath, 'rb')
except FileNotFoundError:
    print('file not found :-(')

    writeFile( tokenFilePath, testdata )
    # refreshing token
    # saving accesstoken, refreshtoken
except:
    print('exception while opening file')

else:
    try:
        filedata = pickle.load(tokenCache)
    except EOFError as error:
        print('file is invalid, trying to write a new one')
        writeFile( tokenFilePath, testdata )
    except:
        print('exception while reading file contents')
    # reading token
    # check for validity
    # if older than 1h, refresh
    else:
        print('reading data worked!')
        pp.pprint( filedata)




#Finally, print check output and exit with rcode
if not perfdata:
    print("{} {}".format( rcstring(rcode), out_text ))
else:
    print("{} {}|{}".format( rcstring(rcode), out_text, perfdata ))

sys.exit(rcode)

# vim: ts=4:expandtab:sw=4:sts=4:ai:smartindent:filetype=python

