#!/usr/bin/env python3
#
# Run checks against HPE Aruba Networking Central
#
# Version 0.1 2025-02-07
#    test version
#
import os, sys
import argparse
import pickle
import requests
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
from lib.generic_plugin import *

# parse command line parameters
cli = argparse.ArgumentParser \
	(description='Maintain Aruba Central token')

cli.add_argument('--id',
        help='Client Id',required = True)
cli.add_argument('--mode',
		help='check mode: wlanap | ...', required = True )
cli.add_argument('--baseurl',
		help='base URL for our acocunt', required = False)
cli.add_argument('--dbdir',
		help='directory where keys are stored', required = False)
cli.add_argument('-d', '--debug', 
		help='enable debugging output', action="store_true")
args = cli.parse_args()

#### init vars
# check output
rcode=0
out_text=''
detail=''
perfdata=''

# arguments / settings
clientId = args.id
baseURL  = args.baseurl or 'https://apigw-eucentral2.central.arubanetworks.com'
dbDir    = args.dbdir or '/var/spool/icinga2/tmp'
# Strip trailing /
dbDir.rstrip('/')
DEBUG		 = args.debug

if DEBUG:
	import pprint
	pp = pprint.PrettyPrinter(indent=4, compact=True, sort_dicts=True)

#-----------------------------------------------------------------------
# Functions
#-----------------------------------------------------------------------

# Handle API Request
def apiRequest( url, method ):
	result = None
	error  = None

	if method == 'post':
		resp = requests.post( url )
	else:
		resp = requests.get( url )

	if resp:
		result = resp.json()
	else:
#		logging.error(
#				"something went wrong\n\nRESP_HEADER\n{}\nRESP_TEXT\n{}".format(
#				resp.headers, resp.text ))
		error=resp.text

	return(result, error)

def readToken( dbDir, clientId ):
	tokenFilePath = dbDir + '/' + clientId + '.token'

	try:
		tokenCache = open(tokenFilePath, 'rb')

	except FileNotFoundError:
		print( plugin_output( 3,
					   'Token file not found. Is the token handler OK?',
					   None, None # Detail, Perfdata
					   )
		)
		sys.exit(3)
	except PermissionError as e:
		print('Internal error: no permission to access DB file')
		sys.exit(3)
	except:
		print('Internal error: exception while opening DB file for reading')
		sys.exit(3)

# File can be read, get information and check whether token renew is due
	else:
		try:
			if DEBUG: print('pickle load')
			filedata = pickle.load(tokenCache)
		except:
			# issue an UNKNOWN here, suggest to delete the file
			print('Internal error: exception while reading file contents')
			sys.exit(3)
		else:
			if DEBUG:
				print('reading data finished!')
				pp.pprint( filedata )
	return


#-----------------------------------------------------------------------
#								  MAIN
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# try to read file
readToken( dbDir, clientId )

#
#Finally, print check output and exit with rcode
#
print( plugin_output( rcode, out_text, detail, perfdata ) )
sys.exit(rcode)

# vim: ts=4:noexpandtab:sw=4:sts=4:ai:smartindent:filetype=python

