#!/usr/bin/env python3

# Feature list:
#  - Check for Endpoint-Status or Device Alerts
#  - Verbose-Switch: Only summarize or print out detailed information
#  - partner-account-mode
#     - specify a tennant-id if you are using a partner-account
#       with multiple tenants
#     - list available tenant-ids and names
#   - individual thesholds for status suspicious, bad, good
#   - individual thesholds for alarm levels high, medium, los
#   - thesholds are merged, most critical wins
#
# Author: m.sander@mr-daten.de
# History:
program_version=str(0.6)
#    Version 0.6  Fri Feb 24 2023
#       First ready-to-use version
#
import requests
import json
import urllib3
#urllib3.disable_warnings()
import logging
import argparse
import sys
import pprint


#
# Check-Plugin functions (move to lib later)
#
def update_rcode(rcode, new):
    if new > rcode:
        rcode = new
    return rcode

def get_rstring(i):
    rstring= {
            0:  '(OK)',
            1:  '(WARNING)',
            2:  '(CRITICAL)',
            3:  '(UNKNOWN)'
            }
    return rstring[i]

#
# functions for login in and get started
#
def get_token(user, pwd):
    url = "{}/api/v2/oauth2/token".format( url_id )
    header = { 'Content-Type': 'application/x-www-form-urlencoded' }
    data="grant_type=client_credentials&client_id={}&client_secret={}&scope=token".format( user, pwd )
    resp = requests.post( url, data=data, headers=header )

    if resp:
        access_token = resp.json().get( 'access_token' )
    else:
        logging.error("something went wrong\n\nRESP_HEADER\n{}\n\nRESP_TEXT\n{}".format( \
                resp.headers, resp.text ))

    return access_token

def whoami( access_token ):
    url = "{}/whoami/v1".format( url_api )
    header = { 'Authorization': "Bearer {}".format(access_token) }
    resp = requests.get( url, headers=header )
    myid = ''
    api =  ''

    if resp:
        json_resp = resp.json()
        myid = json_resp.get('id')
        glob_api = json_resp.get('apiHosts').get('global')
        region_api = json_resp.get('apiHosts').get('dataRegion')

        if region_api != None:  
            api=region_api
        else:
            api=glob_api

    else:
        logging.error("something went wrong\n\nRESP_HEADER\n{}\n\nRESP_TEXT\n{}".format( \
                resp.headers, resp.text ))
    return (myid, api)

#
# functions dealing with tenants
#
def get_tenants( access_token, myid, url_api ):
    url = "{}/partner/v1/tenants".format( url_api )
    header = { 
        'Authorization': "Bearer {}".format(access_token),
        'X-Partner-ID':  myid,
        'Accept': 'application/json'
        }
    resp = requests.get( url + '?pageTotal=true', headers=header )
    return resp.json().get('items')

def list_tenants( tenant_items ):
    list_string=''
    for tenant in tenant_items:
        list_string += "{}: Name: \"{}\"\n".format( tenant['id'], tenant['name'] )
    return list_string

def search_tenant( tenant_items, t_filter):
    list_string=''
    for tenant in  tenant_items:
        if tenant['name'].find(t_filter) >= 0:
            list_string += "{}: Name: \"{}\"\n".format( tenant['id'], tenant['name'] )
    return list_string

def apihost_of_tenant( tenant_id, tenant_items ):
    api_host=None
    for tenant in  tenant_items:
        if tenant['id'] == tenant_id:
            api_host=tenant['apiHost']
    return api_host

#
# Sophos Endpoints
#
def get_endpoints( tenant_id, url_api, health_status=None ):
    if health_status:
        url = "{}/endpoint/v1/endpoints?healthStatus={}&pageTotal=true".format( url_api, health_status )
    else:
        url = "{}/endpoint/v1/endpoints".format( url_api )
    header = { 
        'Authorization': "Bearer {}".format(access_token),
        'X-Tenant-ID':  tenant_id,
        'Accept': 'application/json'
        }
    resp = requests.get( url, headers=header )

    if resp:
        return resp.json().get('items')
    else:
        logging.error("something went wrong in 'get_endpoints'\n\nRESP_HEADER\n{}\n\nRESP_TEXT\n{}".format( \
                resp.headers, resp.text ))
    
#
# Sophos Alerts
#
def get_alerts( tenant_id, url_api, product=None ):
    if product:
        url = "{}/common//v1/alerts?product={}&pageTotal=true".format( url_api, product )
    else:
        url = "{}/common//v1/alerts".format( url_api )
    header = { 
        'Authorization': "Bearer {}".format(access_token),
        'X-Tenant-ID':  tenant_id,
        'Accept': 'application/json'
        }
    resp = requests.get( url, headers=header )

    if resp:
        return resp.json().get('items')
    else:
        logging.error("something went wrong\n\nRESP_HEADER\n{}\n\nRESP_TEXT\n{}".format( \
                resp.headers, resp.text ))

#
# Endpoint Check
#
def check_endpoints( tenant_id, api ):
    # init vars
    final_rcode=0
    status_count={}
    warn = {
        'suspicious' : args.warn_ep_sus,
        'bad' :        args.warn_ep_bad
        }
    crit = {
        'suspicious' : args.crit_ep_sus,
        'bad' :        args.crit_ep_bad
        }

    all_endpoints=get_endpoints( tenant_id, api )

    for ep in all_endpoints:
        if ep.get('health'):
            status = ep.get('health').get('overall')
            if not status_count.get(status):
                status_count[status]={}
                status_count[status]['count'] = 1
                status_count[status]['hosts'] = [ ep.get('hostname') ]
            else:
                status_count[status]['count'] += 1
                status_count[status]['hosts'].append( ep.get('hostname') )
        else:
            status = 'n/a'
            if not status_count.get(status):
                status_count[status]={}
                status_count[status]['count'] = 1
                status_count[status]['hosts'] = [ ep.get('hostname') ]
            else:
                status_count[status]['count'] += 1
                status_count[status]['hosts'].append( ep.get('hostname') )

    # compose check plugin output
    result_message=''
    result_detail=''
    for status in status_count:

        result_message += "{}: {}; ".format( status, status_count[status]['count'] )
        result_detail  += "Endpoints with status {}:\n\t{}\n\n".format( status, status_count[status]['hosts'] )

        if crit.get( status ) and status_count[status]['count'] >= crit[status]:
            final_rcode = update_rcode( final_rcode, 2 )
        elif warn.get( status ) and status_count[status]['count'] >= warn[status]:
            final_rcode = update_rcode( final_rcode, 1 )

    result_string = get_rstring( final_rcode )
    print( "Endpoint overall-health is " + result_string + ': ' + result_message + "\n" )
    if args.print_detail:
        print( result_detail )

    return final_rcode

#
# Alert Check
#
def check_alerts( tenant_id, api, device_type ):
    # init vars
    final_rcode=0
    final_rcode=0
    status_count={}
    warn = {
        'high'  : args.warn_alert_high,
        'medium': args.warn_alert_medium,
        'low'   : args.warn_alert_low
        }
    crit = {
        'high'  : args.crit_alert_high,
        'medium': args.crit_alert_medium,
        'low'   : args.crit_alert_low
        }

    pp = pprint.PrettyPrinter(indent=4, compact=True, sort_dicts=True)
    alerts = get_alerts( tenant_id, api, device_type )

    for alert in alerts:
        severity = alert.get('severity')
        if not status_count.get(severity):
            status_count[severity]={}
            status_count[severity]['count'] = 1
            status_count[severity]['hosts'] = [{ 
                        'name': alert.get('managedAgent').get('name'),
                        'desc': alert.get('description') }]
        else:
            status_count[severity]['count'] += 1
            status_count[severity]['hosts'].append( {
                        'name': alert.get('managedAgent').get('name'),
                        'desc': alert.get('description') } )

        if crit.get( severity ) and status_count[severity]['count'] >= crit[severity]:
            final_rcode = update_rcode( final_rcode, 2 )
        elif warn.get( severity ) and status_count[severity]['count'] >= warn[severity]:
            final_rcode = update_rcode( final_rcode, 1 )
    # compose check plugin output
    result_message=''
    result_detail=''
    for severity in status_count:
        result_message += "{}: {}; ".format( severity, status_count[severity]['count'] )
        result_detail  += "Hosts with alert severity {}:\n{}\n\n".format( severity, \
                                pp.pformat( status_count[severity]['hosts'] ) )

    result_string = get_rstring( final_rcode )
    print( "Alerts for device-type '{}' is {}: ".format( device_type, result_string) + result_message + "\n" )
    if args.print_detail:
        print( result_detail )

    return final_rcode


# # #  # #  # #  # #  # #  # #  # #  # #  # #  # #  # #  # # 
#
# MAIN
#
# # #  # #  # #  # #  # #  # #  # #  # #  # #  # #  # #  # # 

# parse command line parameters

cli = argparse.ArgumentParser \
    (description='Check Sophos Cloud Services for Endpoint-Status or Alerts')

cli.add_argument('--id', dest='client_id',\
        required=True, help='Client ID')
cli.add_argument('--secret', dest='client_secret',\
        required=True, help='Client Secret')
cli.add_argument('--tenant-search', dest='tenant_filter', \
        help='select first tenant found by this substring. Only useful with --atype=partner')
cli.add_argument('--tenant-id', dest='tenant_id',\
        help='Use this Tenant-ID for checks. Only useful with --atype=partner')
cli.add_argument('-v', dest='print_detail', action='store_true', \
        help='Verbose output: append details to check result')
cli.add_argument('--mode', dest='check_mode', default='ep', \
        help='ep|alert')
cli.add_argument('--atype', dest='account_type', default='customer', \
        help='Account Type: \'customer\' or \'partner\'. Default \'customer\'' )
cli.add_argument('--devtype', dest='device_type', default='firewall', \
        help='check devices of this type (e.g. "firewall", "server"). Only has effect\
              with "--mode alert", default is "firewall"')
#cli.add_argument('--detail-severity',  dest='detail_severity', default=None )
cli.add_argument('--warn-ep-sus',  dest='warn_ep_sus', default=None, \
        type=int, help='Warn threshold for status suspicious')
cli.add_argument('--crit-ep-sus',  dest='crit_ep_sus', default=None, \
        type=int, help='Crit threshold for status suspicious')
cli.add_argument('--warn-ep-bad',  dest='warn_ep_bad', default=None,\
        type=int, help='Warn threshold for status bad')
cli.add_argument('--crit-ep-bad',  dest='crit_ep_bad', default=None,\
        type=int, help='Crit threshold for status bad')
cli.add_argument('--warn-alert-high', dest='warn_alert_high', default=None, \
        type=int, help='Warn threshold for "high" alerts')
cli.add_argument('--warn-alert-medium', dest='warn_alert_medium', default=None, \
        type=int, help='Warn threshold for "medium" alerts')
cli.add_argument('--warn-alert-low', dest='warn_alert_low', default=None, \
        type=int, help='Warn threshold for "low" alerts')
cli.add_argument('--crit-alert-high', dest='crit_alert_high', default=None, \
        type=int, help='Crit threshold for "high" alerts')
cli.add_argument('--crit-alert-medium', dest='crit_alert_medium', default=None, \
        type=int, help='Crit threshold for "medium" alerts')
cli.add_argument('--crit-alert-low', dest='crit_alert_low', default=None, \
        type=int, help='Crit threshold for "low" alerts')
cli.add_argument('--version', action='version', version='%(prog)s ' + program_version)
cli.add_argument('--debug', action='store_true')

args = cli.parse_args()

# global parameters
url_id  = 'https://id.sophos.com'
url_api = 'https://api.central.sophos.com'
rcode = 0

# Login and fetch data
access_token = get_token( args.client_id, args.client_secret )
(myid, main_api) = whoami( access_token )

if not args.tenant_id and args.account_type == 'partner':
    #
    # Support and Test Mode; no checks here
    #
    tenant_list = get_tenants( access_token, myid, main_api )
    if args.tenant_filter:
        print("You did not provide tenant-id. Here's a list of tenants according to your search filter:")
        print( search_tenant( tenant_list, args.tenant_filter ), end='' )
        print("----- EOL -----")
    else:
        print("You did not provide a tenant-id. Here's a list of tenants:")
        print( list_tenants( tenant_list), end='' )
        print("----- EOL -----")
else:
    # Account type: partner or 'normal'/customer
    if args.account_type == 'partner':
        tenant_id = args.tenant_id
        tenant_list = get_tenants( access_token, myid, main_api )
        current_api = apihost_of_tenant ( tenant_id, tenant_list )
    else:
        tenant_id = myid
        current_api = main_api

    # Select check type to perform
    if ( args.check_mode == 'ep' ):
        rcode = check_endpoints( tenant_id, current_api )

    elif ( args.check_mode == 'alert'):
        rcode = check_alerts( tenant_id, current_api, args.device_type)

    else:
        logging.error('unknown check mode: ' + check_mode)

sys.exit(rcode)
