#!/usr/bin/env bash

# This plugin retrieves cpu or license status from Sophos XG firewalls
#
# Author: msander
#
# Version: 0.3  2023-03-28
#   new feature and small fixes
#
#    - Added complicated new feature "Sophos Licenses"
#    - Fixed a bug where SNMP-Data was truncated (spaces in output)
#    - Added a 'dbg_msg' function for debugging output to stderr
#    - Fixed indentation
#
## Version: 0.2  2023-03-27
#   fixed perfdata output
#
# Version: 0.1  2023-03-27
#   first version rolled out for testing
#

# Define Vars
declare -A snmpData
declare -A id
declare -A nameMap
declare -a elementList

glob_rcode=0

#
# CLI Parsing
#

OPTERR=1
while getopts "H:C:u:x:X:a:A:l:w:c:m:f:F:t:Bhd" OPTION ; do
    case "${OPTION}" in
        H) hostname=${OPTARG}       ;;
        C) community="-c ${OPTARG}" ;;
        u) authuser="-u ${OPTARG}"  ;;
        a) authproto="-a ${OPTARG}" ;;
        A) authpass="-A ${OPTARG}"  ;;
        x) privproto="-x ${OPTARG}" ;;
        X) privpass="-X ${OPTARG}"  ;;
        l) seclevel="-l ${OPTARG}"  ;;
        w) warn=${OPTARG}           ;;
        c) crit=${OPTARG}           ;;
        m) mode=${OPTARG}           ;;
        f) filter=${OPTARG}         ;;
        F) neg_filter=${OPTARG}     ;;
        t) tout=${OPTARG}           ;;
        B) nobulk=1                 ;;
        h) helpme=1                 ;;
        d) debug=1                  ;;
    esac
done

#######
# Functions
#######

function check_arguments {
        if [ -z "$hostname" ] ; then
                echo "$0 required argument -H <hostname> missing"
                exit 3
        elif [ -z "$authuser" -a -z "$community" ] ; then
                echo "$0 SNMP credentials missing: either -C <community> or snmp V3:"
                echo "  -u <authuser> -a <authproto> -A <authpass> -x <secproto> -X <secpass> -l <seclevel>"
                exit 3
        fi
}

function dbg_msg {
    if [ "$debug" ] ; then
        >&2 echo "DEBUG: $1"
    fi
}


function percent() {
    local total=$1
    local part=$2
    $bc -l <<< "scale=4; r( ($part / $total * 100), 0 )"
}

function calc_state() {
    local value=$1;local warn=$2;local crit=$3;local rcode

    if [ $value -gt $crit ] ; then
        rcode=2
    elif [ $value -gt $warn ] ; then
        rcode=1
    else
        rcode=0
    fi
    echo $rcode
}

# take into account the current global return code
function calc_globalstate() {
    local value=$1;local warn=$2;local crit=$3;local rcode

    rcode=$( calc_state $value $warn $crit )

    if [ $rcode -le $glob_rcode ] ; then
        rcode=$glob_rcode
    else
        rcode=$rcode
    fi
    echo $rcode
}

function set_globalstate() {
    local rcode=$1

    if [ $rcode -le $glob_rcode ] ; then
        rcode=$glob_rcode
    else
        rcode=$rcode
    fi
    echo $rcode
}

function state_string() {
    local rcode=$1
    local string
    case $rcode in 
        0) string='(OK):' ;;
        1) string='(WARNING):' ;;
        2) string='(CRITICAL):' ;;
        3) string='(UNKNOWN):' ;;
    esac
    echo $string
}

function mode_string() {
    local mode=$1
    local string
    case $mode in 
        cpu) string='CPU' ;;
        license) string='Licenses' ;;
    esac
    echo $string
}

function date_to_epoch {
    # Try to convert various date formats to epoch seconds

    local regex[0]='[A-Z][a-z]{2} +[0-9]+ [0-9]{4}"'
    local datefmt[0]='"%b %e %Y"'
    local regex[1]='([A-Z][a-z]{2} ){2} *[0-9]+ ([0-9]{2}:){2}[0-9]{2} [0-9]{4}'
    local datefmt[1]='"%a %b %e %T %Y"'
    local input="$1"
    local epoch=0

    for re in 0 1 ; do
        if [[ "$input" =~ ${regex[$re]} ]] ; then
        dbg_msg "Date $input matches ${regex[$re]}"
            epoch=$( date -j -f "${datefmt[$re]}" "$input" +%s )
    else
        dbg_msg "Date $input NOT matches ${regex[$re]}"
    fi
    done

    echo $epoch
}

# generate human readable bytes
function hr_bytes() {
    local rawbyte=$1
    local bstr=Byte

    # more than 10 TB
    if [ $rawbyte -gt 10000000000000 ] ;then
        hrbyte="$(( $rawbyte>>40 )) T$bstr"

    # more than 10 GB
    elif [ $rawbyte -gt 10000000000 ] ;then
        hrbyte="$(( $rawbyte>>30 )) G$bstr"

    # more than 10 MB
    elif [ $rawbyte -gt 10000000 ] ;then
        hrbyte="$(( $rawbyte>>20 )) M$bstr"
    fi

    echo $hrbyte
}

function raid_byfilter() {
    # Print Out Data for Elements, filtered by Name
    # By default, select all elements

    local filter=$1

    for eName in ${!nameMap[@]}
    do
        if [[  "$eName" =~ $filter ]]
        then
            outElements+=(${nameMap[$eName]})
        fi
    done

    local loop_rcode=0
    local loop_state
    for element in  ${outElements[@]}
    do
        name=${snmpData[${baseOID}.${id[name]}.$element]}
        size_bytes=${snmpData[${baseOID}.${id[size]}.$element]}
        raid_status=${snmpData[${baseOID}.${id[status]}.$element]}

        # Check Status
        case $raid_status in
            '"Ready"')
                loop_rcode=0;;
            '"Degraded"')
                loop_rcode=1;;
        esac
        loop_state=$( state_string $loop_rcode )
        glob_rcode=$( set_globalstate $loop_rcode ) 

        # text output
        outmsg+="RAID $name: Capacity $(( size_bytes>>30 )) GB, Status $raid_status; "
        details+="$loop_state $name\n"
        details+="  Size:   $( hr_bytes $size_bytes )\n"
        details+="  Status: $raid_status\n\n"
    done
}

function get_snmp {
    #
    # Compose snmp command
    #
    if [ "$nobulk" ]; then walk=snmpwalk;  else walk=snmpbulkwalk; fi
    if [ -n "$authuser" ]; then snmpv=3; else snmpv=2c; fi

    snmpcmd="$walk -Onq -v $snmpv -t $tout -r 3 \
        $community $authuser $privproto $privpass $seclevel $authproto $authpass \
        $hostname  $baseOID"

    dbg_msg "debug snmpcmd: $snmpcmd"


    # First of all, get the SNMP-Data
    snmpResponse=$($snmpcmd 2>&1)
    snmpexit=$?

    dbg_msg "debugsnmpresponse: $snmpResponse"

    if [ $snmpexit -ne 0 ] ; then
        echo "(UNKNOWN): Problem fetching SNMP data."
        echo 
        echo "SNMP Output was: $snmpResponse"
        exit 3
    fi

    while read oid value
    do 
        snmpData[$oid]="$value"
    done <<< "$snmpResponse"
}

function process_snmp_index {
    #### building indexes
    #

    # build element index
    for key in ${!snmpData[@]} ; do
        if [[ $key == "$baseOID.${id[index]}"* ]] ; then
        elementIndex+=( ${snmpData[$key]} )
        fi
    done

    # build name map
    for element in  ${elementIndex[@]}
    do
        nameMap[${snmpData[${baseOID}.${id[name]}.$element]}]=${snmpData[${baseOID}.${id[index]}.$element]}
    done
    #
    #
    #### / building indexes
}

function process_snmp_noindex {
    #### building indexes
    #

    # build element list
    local element_counter=0
    for element in ${snmpData[@]} ; do
            elementList[$element_counter]=$element
            : $(( element_counter++ ))
    done
}

function cpu_check {
    local cpu_percent
    local cpu_sum=0
    local cpu_avg
    local cpu_count=${#elementList[@]}
    local cpu_warn=${warn:-0}
    local cpu_crit=${crit:-0}

    if [ $cpu_count -gt 1 ] ; then
        # sum up cpu percents
        for cpu_item in ${elementList[@]} ; do
            cpu_sum=$(( cpu_sum + cpu_item ))
        done
        cpu_avg=$(( cpu_sum / cpu_count ))
    else
        cpu_avg=${elementList[0]}
    fi

    glob_rcode=$( set_globalstate 0 )
    # text output
    outmsg+="Average CPU utiliziation ${cpu_avg}%"
    perfdata+="avg_cpu=${cpu_avg}%;$cpu_warn"

    if [ $cpu_count -gt 1 ] ; then
        for cpu_index in ${!elementList[@]} ; do
            perfdata+=" cpu_${cpu_index}=${elementList[$cpu_index]}%;$cpu_warn;$cpu_crit"
        done
    fi
}

function license_check {
    local licenseNames=( Base NetProtect WebProtect MailProtect WebServer Sandstorm EnhancedSupport EnhancedPlusSupport  C-Orchestration )
    local subOID
    local licStatus
    # Beware! We need negative values here
    local lic_warn=-${warn:-30}
    local lic_crit=-${crit:-7}
    local lic_rcode=0
    local loop_rcode=0
    local lic_data_invalid=0
    local licenseCounter[1]=0
    local licenseCounter[2]=0
    local licenseCounter[3]=0
    local licenseCounter[4]=0
    local statusNames=( none trial unsubscribed subscribed expired )
    # Seconds per Day
    local s2d=86400

    local epoch_current=`date +%s`

    details+='Licenses in detail:\n'

    for licIndex in ${!licenseNames[@]}; do
            # Skip 'Base' license because it has no usabel value
            if [ $licIndex -eq 0 ] ; then continue ; fi

            # License Status
            subOID="${baseOID}.$(( licIndex +1 )).1.0"
            licStatus=${snmpData[$subOID]}
            licenseCounter[$licStatus]=$(( licenseCounter[$licStatus] + 1 ))

            # Expiry Date
            subOID="${baseOID}.$(( licIndex +1 )).2.0"
            human_expire=${snmpData[$subOID]}

            # Special Case invalid date from snmp
            if [ "$human_expire" == '"fail"' -o "$human_expire" == '' ] ; then 
                lic_data_invalid=1
        else
            lic_data_invalid=0
        fi

        if [ $lic_data_invalid -ne 1 ] ; then
            epoch_expire=$( date_to_epoch "$human_expire" )
            days_til_expire=$(( (epoch_expire - epoch_current) / s2d ))

            # skip state calculations when status is 'expired/4' anyway
            if [ $licStatus -eq 4 ] ; then
                loop_rcode=2
            else 
                loop_rcode=$( calc_state $(( -$days_til_expire )) $lic_warn $lic_crit )
            fi

            # different output text when exp. date is negative
            if [ $days_til_expire -gt 0 ] ; then
                expday_text='days until '
                exp_text='expires'
            else
                expday_text='days since '
                exp_text='expired'
            fi

            glob_rcode=$( set_globalstate $loop_rcode )
            loop_line=$( printf "%-10s %4s $expday_text %19s $exp_text on $human_expire, status \"${statusNames[$licStatus]}\""  `state_string $loop_rcode` $days_til_expire "${licenseNames[$licIndex]}" )

        else
            loop_line=$( printf "(no license?): no date for  %19s expiration date unknown, status \"${statusNames[$licStatus]}\"\n" "${licenseNames[$licIndex]}" )
        fi

        details+="   $loop_line\n"
    done

    outmsg+="Number of Licenses: Trial = ${licenseCounter[1]}, Unsubscribed = ${licenseCounter[2]}, Subscribed = ${licenseCounter[3]}, Expired = ${licenseCounter[4]}"
}

#
# MAIN
#

#
# set default values
#
mode=${mode:=cpu}
filter=${filter:=.}
tout=${tout:=20}

check_arguments
# 
# precission calculator 'bc' compat. check
#
if [ -x /usr/local/bin/bc ]; then 
    bc=/usr/local/bin/bc
elif [ -x /usr/bin/bc ] ; then
    bc=/usr/bin/bc
fi

case $mode in
    cpu)
        baseOID='.1.3.6.1.2.1.25.3.3.1.2'
        get_snmp
        process_snmp_noindex
        cpu_check
    ;;

        license)
        baseOID='.1.3.6.1.4.1.2604.5.1.5'
        get_snmp
        license_check
    ;;
    
    #volume)
    #    baseOID='.1.3.6.1.4.1.55062.1.10.9.1'
    #    id[index]=1
    #    id[name]=8
    #    id[size]=3
    #    id[free]=4
    #    id[status]=5
    #    get_snmp_and_process 
    #    storage_byfilter $filter
    #;;
    
    *)
        echo "(UNKNOWN): mode '-m $mode' not known" ; exit 3 ;;
esac


#
# Tell monitoring system what we found out
#
echo -en "$( state_string $glob_rcode ) $outmsg"
if [ -n "$details" ] ; then echo -en "\n\n$details" ; fi
if [ -n "$perfdata" ] ; then echo -en "|$perfdata" ; fi
echo

exit $glob_rcode


#vim: set ts=4 expandtab sw=4
