#!/usr/bin/env bash

# This plugin retrieves various informations from Lenovo XCC Controllers
# (aka XClatiry)
#
# Author: msander
#
# Version: 0.1  2025-02-03
#   first test version
#

# Define Vars
declare -A snmpData
declare -A id
declare -A nameMap
declare -a elementList

glob_rcode=0

#
# CLI Parsing
#

OPTERR=1
while getopts "H:C:u:x:X:a:A:l:w:c:m:f:F:t:Bhd" OPTION ; do
    case "${OPTION}" in
        H) hostname=${OPTARG}       ;;
        C) community="-c ${OPTARG}" ;;
        u) authuser="-u ${OPTARG}"  ;;
        a) authproto="-a ${OPTARG}" ;;
        A) authpass="-A ${OPTARG}"  ;;
        x) privproto="-x ${OPTARG}" ;;
        X) privpass="-X ${OPTARG}"  ;;
        l) seclevel="-l ${OPTARG}"  ;;
        w) warn=${OPTARG}           ;;
        c) crit=${OPTARG}           ;;
        m) mode=${OPTARG}           ;;
        f) filter=${OPTARG}         ;;
        F) neg_filter=${OPTARG}     ;;
        t) tout=${OPTARG}           ;;
        B) nobulk=1                 ;;
        h) helpme=1                 ;;
        d) debug=1                  ;;
    esac
done

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Load library functions
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

callpath="$(dirname "$0")"
libdir="${callpath}/../lib"

source $libdir/generic_plugin.shlib
source $libdir/generic_snmp.shlib

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Local functions
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

function global_health {
	local globHealth="${snmpData[$baseOID]}"
	hcomment[0]='Non Recoverable'
	hcomment[2]='Critical'
	hcomment[4]='Non Critical'
	hcomment[255]='Normal'

	hlevel[0]=2
	hlevel[2]=2
	hlevel[4]=1
	hlevel[255]=0

	if [ -z "${hlevel[$globHealth]}" ] ; then
		outmsg="Global Health status responded with unknown state '$globHealth'"
		glob_rcode=3
	else
		glob_rcode=${hlevel[$globHealth]}
		outmsg="Global Health status is '${hcomment[$globHealth]}'"
	fi
}

#
# MAIN
#

#
# set default values
#
mode=${mode:=global_health}
filter=${filter:=.}
tout=${tout:=20}

check_snmp_args

case $mode in

    #sysinfo)
    #    #AgentInfo
    #    baseOID='.1.3.6.1.4.1.231.2.10.2.2.10.1'
    #    get_snmp
    #    get_systeminfo
    #;;

	global_health)
		baseOID='.1.3.6.1.4.1.19046.11.1.1.4.1.0'
		get_snmp_lib units nobulk
		global_health
	;;
    
    *)
        echo "(UNKNOWN): mode '-m $mode' not known" ; exit 3 ;;
esac


#
# Tell monitoring system what we found out
#
trigger_exit

#vim: set ts=4 expandtab sw=4
