#!/usr/bin/env bash

# This plugin retrieves various informations from Dell iDRAC Boards.
#
# Author: msander
#
# Version: 0.2  2023-04-11
#   removed useless tab in check output
# Version: 0.1  2023-03-29
#   first test version
#

# Define Vars
declare -A snmpData
declare -A id
declare -A nameMap
declare -a elementList

glob_rcode=0

#
# CLI Parsing
#

OPTERR=1
while getopts "H:C:u:x:X:a:A:l:w:c:m:f:F:t:Bhd" OPTION ; do
    case "${OPTION}" in
        H) hostname=${OPTARG}       ;;
        C) community="-c ${OPTARG}" ;;
        u) authuser="-u ${OPTARG}"  ;;
        a) authproto="-a ${OPTARG}" ;;
        A) authpass="-A ${OPTARG}"  ;;
        x) privproto="-x ${OPTARG}" ;;
        X) privpass="-X ${OPTARG}"  ;;
        l) seclevel="-l ${OPTARG}"  ;;
        w) warn=${OPTARG}           ;;
        c) crit=${OPTARG}           ;;
        m) mode=${OPTARG}           ;;
        f) filter=${OPTARG}         ;;
        F) neg_filter=${OPTARG}     ;;
        t) tout=${OPTARG}           ;;
        B) nobulk=1                 ;;
        h) helpme=1                 ;;
        d) debug=1                  ;;
    esac
done

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Load library functions
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

callpath="$(dirname "$0")"
libdir="${callpath}/../lib"

source $libdir/generic_plugin.shlib
source $libdir/generic_snmp.shlib
source $libdir/convert_and_calc.shlib

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Local functions
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #


function get_snmp {
    #
    # Compose snmp command
    #
    if [ "$nobulk" ]; then walk=snmpwalk;  else walk=snmpbulkwalk; fi
    if [ -n "$authuser" ]; then snmpv=3; else snmpv=2c; fi

    snmpcmd="$walk -Onq -v $snmpv -t $tout -r 3 \
        $community $authuser $privproto $privpass $seclevel $authproto $authpass \
        $hostname  $baseOID"

    dbg_msg "debug snmpcmd: $snmpcmd"


    # First of all, get the SNMP-Data
    snmpResponse=$($snmpcmd 2>&1)
    snmpexit=$?

    dbg_msg "debugsnmpresponse: $snmpResponse"

    if [ $snmpexit -ne 0 ] ; then
        echo "(UNKNOWN): Problem fetching SNMP data."
        echo 
        echo "SNMP Output was: $snmpResponse"
        exit 3
    fi

    while read oid value
    do 
        snmpData[$oid]="$value"
    done <<< "$snmpResponse"
}

function process_snmp_index {
    #### building indexes
    #

    # build element index
    for key in ${!snmpData[@]} ; do
        if [[ $key == "$baseOID.${id[index]}"* ]] ; then
        elementIndex+=( ${snmpData[$key]} )
        fi
    done

    # build name map
    for element in  ${elementIndex[@]}
    do
        nameMap[${snmpData[${baseOID}.${id[name]}.$element]}]=${snmpData[${baseOID}.${id[index]}.$element]}
    done
    #
    #
    #### / building indexes
}

function process_snmp_noindex {
    #### building indexes
    #

    # build element list
    local element_counter=0
    for element in ${snmpData[@]} ; do
            elementList[$element_counter]=$element
            : $(( element_counter++ ))
    done
}

function idrac_status {
    local enum=$1
    local map=( dummy other unknown ok nonCritical critical nonRecoverable )
    if [ -z "${map[$enum]}" ] ; then
        dbg_msg "unknown state: $enum" ; exit 10
    fi
    echo "${map[$enum]}"
}

function idrac_state {
    local enum=$1
    local map=( dummy other unknown off on )
    if [ -z "${map[$enum]}" ] ; then
        dbg_msg "unknown state: $enum" ; exit 10
    fi
    echo "${map[$enum]}"
}

function check_globalstatus {
    local oid_names[1]='Global System Status'
    local oid_names[2]='LCD Status'
    local oid_names[3]='Storage Status'
    local oid_names[4]='Power State'
    local curOID
    local curStat
    local loop_status
    local loop_line

    details+="Details:\n"
    outmsg='iDRAC overall status'
    for key in ${!oid_names[@]} ; do
        curOID="${baseOID}.$key.0"
        if [ $key -ne 4 ] ; then 
            # Other Status
            if [ ${snmpData[$curOID]} -lt 4 ]  ; then 
                loop_status=0
            elif [ ${snmpData[$curOID]} -eq 4 ] ; then
                loop_status=1
            elif [ ${snmpData[$curOID]} -gt 4 ] ; then
                loop_status=2
            fi
            curStat=`idrac_status ${snmpData[$curOID]}`

        else
            # Power State
            if [ ${snmpData[$curOID]} -eq 4 ]  ; then 
                loop_status=0
            elif [ ${snmpData[$curOID]} -lt 4 ] ; then
                loop_status=1
            fi
            curStat=`idrac_state ${snmpData[$curOID]}`
        fi
        loop_line=$( printf "%12s %-22s is %-15s" `state_string $loop_status` \
            "${oid_names[$key]}"  ${curStat^^} )
        details+="  $loop_line\n"
        glob_rcode=$( set_globalstate $loop_status ) 
    done
}

function get_systeminfo {
    declare -A oid_names
    oid_names[1.1]='Name'
    oid_names[1.2]='Short Name'
    oid_names[1.5]='Card Version'
    oid_names[1.6]='Card URL'
    oid_names[1.8]='Firmware Version'
    oid_names[3.1]='System FQDN'
    oid_names[3.12]='System Model'
    local max_length=${#oid_names['1.8']}
    local loop_line

    # Put firmware into the first line
    local firmware=${snmpData[${baseOID}.1.8.0]}
    outmsg="System Info of 'Remote Access Card' (Firmware ${firmware//\"/})"

    for key in ${!oid_names[@]} ; do
        curOID="${baseOID}.$key.0"
        curValue=${snmpData[$curOID]//\"/}
        loop_line=$( printf "%-${max_length}s: $curValue" "${oid_names[$key]}"  )
        details+="$loop_line\n"
        
    done

}

function check_uptime {
    uptime_sec=${snmpData[$baseOID]}
    outmsg="Chassis Uptime `second_to_hr $uptime_sec`"
    perfdata="uptime_sec=${uptime_sec}s"
}

#
# MAIN
#

#
# set default values
#
mode=${mode:=globalstatus}
filter=${filter:=.}
tout=${tout:=20}

check_snmp_args
# 
# precission calculator 'bc' compat. check
#
if [ -x /usr/local/bin/bc ]; then 
    bc=/usr/local/bin/bc
elif [ -x /usr/bin/bc ] ; then
    bc=/usr/bin/bc
fi

case $mode in
    globalstatus)
        baseOID='.1.3.6.1.4.1.674.10892.5.2'
        get_snmp
        check_globalstatus
    ;;

    sysinfo)
        baseOID='.1.3.6.1.4.1.674.10892.5.1'
        get_snmp
        get_systeminfo
    ;;

    uptime)
        baseOID='.1.3.6.1.4.1.674.10892.5.2.5.0'
        get_snmp
        check_uptime
    ;;
    
    *)
        echo "(UNKNOWN): mode '-m $mode' not known" ; exit 3 ;;
esac


#
# Tell monitoring system what we found out
#
echo -en "$( state_string $glob_rcode ) $outmsg"
if [ -n "$details" ] ; then echo -en "\n\n$details" ; fi
if [ -n "$perfdata" ] ; then echo -en "|$perfdata" ; fi
echo

exit $glob_rcode


#vim: set ts=4 expandtab sw=4
