#!/usr/bin/env python3
#
# Check FortiSwitch via API
#
program_version=str(0.2)
# Version 0.2 - ram and cpu
# Version 0.1 - initial test
#

import requests, json
import os, sys
import argparse
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
from lib.generic_plugin import *

requests.urllib3.disable_warnings()
# parse command line parameters
cli = argparse.ArgumentParser \
	(description='Maintain Aruba Central token')

cli.add_argument('--hostname', '-H', required = True,
		help='Switch IP or FQDN' )
cli.add_argument('--user', '-u', required = True,
		help='FortiSwitch User')
cli.add_argument('--password', '-p', required = True,
		help='FortiSwitch Password')
cli.add_argument('--apiversion', '-a', required = False, 
		default='7.6.1', help='use this api version' )
cli.add_argument('--mode', '-m', required = True,
		help='choose which check to perform' )
cli.add_argument('--warn', '-w', help='warning threshold' )
cli.add_argument('--crit', '-c', help='critical threshold' )
cli.add_argument('-d', '--debug',
		help='enable debugging output', action="store_true")
cli.add_argument('--version',
		action='version', version='%(prog)s ' + program_version)
args = cli.parse_args()

DEBUG=args.debug
#-----------------------------------------------------------------------
# Functions
#-----------------------------------------------------------------------
def login(host,user,passwd,port=False):
	if port:
		host = f'{host}:{port}'
	url_login = f'https://{host}/logincheck'
	client = requests.session()

	#payload = "username=mradmin&secretkey=etpGKYccj76QMWPbIKQU"
	payload = "username={}&secretkey={}".format( user, passwd )

	r = client.post(url_login, data=payload, verify=False)
	apscookie=r.cookies

	for cookie in client.cookies:
		if cookie.name == 'ccsrftoken':
			csrftoken = cookie.value[1:-1] # token stored as a list

	client.headers.update({'X-CSRFTOKEN': csrftoken})

	return client, apscookie

def request(client, cookie, url):
	result = None
	error  = None
	resp = client.get( url, verify=False, cookies=cookie )
	if resp and (
		'application/json' in resp.headers.get('Content-Type', '')
		):
		result = resp.json()
	else:
		error=resp.text
	return(result, error)

def check_cpu(answer, warn, crit):
	cpus=[]
	sum=0
	for cpu in answer.get('results').get('cpu'):
		cpus.append(cpu)
		sum+=cpu
	
	avg = sum / len( cpus )
	out=f'Average CPU usage {avg:.0f}%'
	if DEBUG:
		pp.pprint( answer )
		pp.pprint( cpus )
		print( 'average ', avg)

	return( out ) 

def check_mem(answer, warn, crit):
	mem=answer.get('results').get('mem')
	out=f'Memory Usage: {mem}%'
	return( out )

#-----------------------------------------------------------------------
#								  MAIN
#-----------------------------------------------------------------------

# init vars?
rcode=0;out_text='';detail='';perfdata=''
if DEBUG:
	import pprint
	pp=pprint.PrettyPrinter(indent=4)

if args.mode == 'info':
	# Login
	client, cookie = login( args.hostname, args.user, args.password )

	# Get resources (mem, cpu in %)
	url=f'https://{ args.hostname }/api/v{ args.apiversion }/monitor/system/resource'

	response = client.get( url, verify=False, cookies=cookie )
	print( response.text )
elif args.mode == 'psu':
	True
elif args.mode == 'fan':
	True
elif args.mode == 'cpu':
	# Login
	client, cookie = login( args.hostname, args.user, args.password )

	# Get resources (mem, cpu in %)
	url=f'https://{ args.hostname }/api/v{ args.apiversion }/monitor/system/resource'
	( answer, error ) = request( client, cookie, url )

	out_text = check_cpu( answer, args.warn, args.crit )

elif args.mode == 'ram':
	# Login
	client, cookie = login( args.hostname, args.user, args.password )

	# Get resources (mem, cpu in %)
	url=f'https://{ args.hostname }/api/v{ args.apiversion }/monitor/system/resource'
	( answer, error ) = request( client, cookie, url )

	out_text = check_mem( answer, args.warn, args.crit )

else:
	rcode=3
	out_text='Unknown value for "--mode": {}'.format( args.mode ) 

# url='https://10.56.198.2/api/v6.4.3/monitor/hardware/cpu'
# response = client.get( url,verify=False, cookies=cookie )
# print( response.text )
# 
# url='https://10.56.198.2/api/v6.4.3/monitor/hardware/memory'
# response = client.get( url,verify=False, cookies=cookie )
# print( response.text )
# 
# url='https://10.56.198.2/api/v6.4.3/monitor/system/psu-status'
# response = client.get( url,verify=False, cookies=cookie )
# print( response.text )
# 
# url='https://10.56.198.2/api/v6.4.3/monitor/system/fan-status'
# response = client.get( url,verify=False, cookies=cookie )
# print( response.text )

print( plugin_output(rcode, out_text, detail, perfdata) )
sys.exit(rcode)

# vim: ts=4:noexpandtab:sw=4:sts=4:ai:smartindent:filetype=python
