#!/usr/bin/env python3
#
# Check FortiSwitch via API
#
program_version=str(1.4)
# Version 1.4 - Fans: Also count 'Good' as 'OK'
# Version 1.3 - Fixed and simplified Fan-Check (failed for multiple fans)
# Version 1.2 - finalized PSU check
# Version 1.1 - template for future license check
# Version 1.0 - 1st productive version
# Version 0.4 - system info
# Version 0.3 - fans, psu, perfdatas, thesholds
# Version 0.2 - ram and cpu
# Version 0.1 - initial test
#

import requests, json
import os, sys
import argparse
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
from lib.generic_plugin import *

requests.urllib3.disable_warnings()
# parse command line parameters
cli = argparse.ArgumentParser \
	(description='Maintain Aruba Central token')

cli.add_argument('--hostname', '-H', required = True,
		help='Switch IP or FQDN' )
cli.add_argument('--user', '-u', required = True,
		help='FortiSwitch User')
cli.add_argument('--password', '-p', required = True,
		help='FortiSwitch Password')
cli.add_argument('--apiversion', '-a', required = False, 
		default='7.6.1', help='use this api version' )
cli.add_argument('--mode', '-m', required = True,
		help='choose which check to perform' )
cli.add_argument('--warn', '-w', type=int, help='warning threshold' )
cli.add_argument('--crit', '-c', type=int, help='critical threshold' )
cli.add_argument('-d', '--debug',
		help='enable debugging output', action="store_true")
cli.add_argument('--version',
		action='version', version='%(prog)s ' + program_version)
args = cli.parse_args()

DEBUG=args.debug
#-----------------------------------------------------------------------
# Functions
#-----------------------------------------------------------------------
def login(host,user,passwd,port=False):
	if port:
		host = f'{host}:{port}'
	url_login = f'https://{host}/logincheck'
	client = requests.session()

	#payload = "username=mradmin&secretkey=etpGKYccj76QMWPbIKQU"
	payload = "username={}&secretkey={}".format( user, passwd )

	r = client.post(url_login, data=payload, verify=False)
	if not r.cookies:
		out_text = 'Can not login. Check credentials.'
		print( plugin_output(3, out_text, None, None) )
		sys.exit(3)
	else:
		apscookie=r.cookies

	for cookie in client.cookies:
		if cookie.name == 'ccsrftoken':
			csrftoken = cookie.value[1:-1] # token stored as a list

	client.headers.update({'X-CSRFTOKEN': csrftoken})

	return client, apscookie

def request(client, cookie, url):
	result = None
	error  = None
	resp = client.get( url, verify=False, cookies=cookie )
	if resp and (
		'application/json' in resp.headers.get('Content-Type', '')
		):
		result = resp.json()
	else:
		error=resp.text
	return(result, error)

def get_info(answer):
	rcode=0
	detail=''
	out=''
	fields={
			'hostname': 'Hostname',
			'serial_number': 'S/N',
			'version': 'Version',
			'system_part_number': 'Part-No.',
			'BIOS_version': 'BIOS-Version',
		 }

	if answer.get('results'):
		for key in fields.keys():
			value = answer.get('results').get(key)
			if not value: value = '-unknown-'
			detail += f'{fields[key]:15}: {value}\n'
		out = 'System Info'
	else:
		out = 'No system info found'
		rcode=3

	return( rcode, out, detail )

# TODO / not ready
def get_license(answer):
	rcode=0
	detail=''
	out=''
	return( rcode, out, detail )

def check_psu(answer):
	rcode=0
	out=''; perf=''

	if len(answer.get('results')) > 0:
		for psu in answer.get('results'):
			name = psu.get('name')
			stat = psu.get('status')
			if stat != 'OK':
				rcode = update_rc( 1, rcode )
			out += f'{name}: {stat}; '
	else:
		#  No PSUs 
		out = 'No PSUs found on this device'

	return( rcode, out, perf )

def check_fan(answer):
	rcode=0
	out=''; out_warn=''; perf=''

	if len(answer.get('results')) > 0:
		# 
		# There are Fans
		#

		# normalizing data info 'fans'
		for fan in answer.get('results'):
			name  = fan.get('module')
			speed = fan.get('speed').get('value')
			unit  = fan.get('speed').get('unit')
			state = fan.get('status')
			if unit != '%':
				out_warn = 'Warning! Unsupported speed unit'
			else:
				if state not in ['OK', 'Good']:
					rcode = update_rc( 2, rcode )

				out  += f"{name} [{state}] {speed:.0f}%; "
				perf += f'{name}={speed:.0f}% '

	else:
		# 
		#  We don't have any Fans
		#
		out = 'No Fans found on this device'

	out  += out_warn
	return( rcode, out, perf )

def check_cpu(answer, warn, crit):
	rcode=0
	cpus=[]
	sum=0
	for cpu in answer.get('results').get('cpu'):
		cpus.append(cpu)
		sum+=cpu
	
	avg = sum / len( cpus )
	rcode = check_threshold( avg, warn, crit )
	out=f'Average CPU usage {avg:.0f}%'
	perf = f'cpu={avg:.0f}%;{warn};{crit} '
	return( rcode, out, perf ) 

def check_mem(answer, warn, crit):
	rcode=0
	mem=answer.get('results').get('mem')
	rcode = check_threshold( mem, warn, crit )
	out  = f'Memory Usage: {mem}%'
	perf = f'mem={mem}%;{warn};{crit}'
	return( rcode, out, perf )

def set_errormsg(error):
	rcode = 3
	out = 'An error occured. Details below.'
	detail = error
	return( rcode, out, detail )

#-----------------------------------------------------------------------
#								  MAIN
#-----------------------------------------------------------------------

# init vars?
rcode=0;out_text='';detail='';perfdata=''

if DEBUG:
	import pprint
	pp=pprint.PrettyPrinter(indent=4)

if args.mode == 'info':
	# Login
	client, cookie = login( args.hostname, args.user, args.password )
	url=f'https://{ args.hostname }/api/v{ args.apiversion }/monitor/system/status'
	( answer, error ) = request( client, cookie, url )
	if error:
		( rcode, out_text, detail ) = set_errormsg( error )
	else:
		( rcode, out_text, detail ) = get_info( answer )

# TODO / feature not required yet
elif args.mode == 'license':
	# Login
	client, cookie = login( args.hostname, args.user, args.password )
	url=f'https://{ args.hostname }/api/v{ args.apiversion }/monitor/switch/capabilities'
	( answer, error ) = request( client, cookie, url )
	if error:
		( rcode, out_text, detail ) = set_errormsg( error )
	#else:
		#( rcode, out_text, detail ) = get_license( answer )


elif args.mode == 'psu':
	# Login
	client, cookie = login( args.hostname, args.user, args.password )
	url=f'https://{ args.hostname }/api/v{ args.apiversion }/monitor/system/psu-status'

	( answer, error ) = request( client, cookie, url )
	if error:
		( rcode, out_text, detail ) = set_errormsg( error )
	else:
		( rcode, out_text, perfdata ) = check_psu( answer )

elif args.mode == 'fan':
	# Login
	client, cookie = login( args.hostname, args.user, args.password )
	url=f'https://{ args.hostname }/api/v{ args.apiversion }/monitor/system/fan-status'

	( answer, error ) = request( client, cookie, url )
	if error:
		( rcode, out_text, detail ) = set_errormsg( error )
	else:
		( rcode, out_text, perfdata ) = check_fan( answer )

elif args.mode == 'cpu':
	# Login
	client, cookie = login( args.hostname, args.user, args.password )
	url=f'https://{ args.hostname }/api/v{ args.apiversion }/monitor/system/resource'

	( answer, error ) = request( client, cookie, url )
	if error:
		( rcode, out_text, detail ) = set_errormsg( error )
	else:
		( rcode, out_text, perfdata ) = check_cpu( answer, args.warn, args.crit )

elif args.mode == 'ram':
	# Login
	client, cookie = login( args.hostname, args.user, args.password )

	# Get resources (mem, cpu in %)
	url=f'https://{ args.hostname }/api/v{ args.apiversion }/monitor/system/resource'
	( answer, error ) = request( client, cookie, url )
	if error:
		( rcode, out_text, detail ) = set_errormsg( error )
	else:
		( rcode, out_text, perfdata ) = check_mem( answer, args.warn, args.crit )

else:
	rcode=3
	out_text='Unknown value for "--mode": {}'.format( args.mode ) 

if DEBUG:
	if answer:
		pp.pprint(answer)
	if error:
		pp.pprint(error)

print( plugin_output(rcode, out_text, detail, perfdata) )
sys.exit(rcode)

# vim: ts=4:noexpandtab:sw=4:sts=4:ai:smartindent:filetype=python:nofoldenable
