#!/usr/bin/env bash
callpath=`dirname $0`
LIBPATH=$callpath/../lib
. $LIBPATH/bashPluginFunctions.sh

OPTERR=1
while getopts "s:k:m:" OPTION ; do
    case "$OPTION" in
    s)  serial="$OPTARG"    ;;
    k)  apikey="$OPTARG"    ;;
    m)  meraki_url="$OPTARG" ;;
    ?)   exit 3 ;;
    esac
done

if [ -z "$serial" -o -z "$apikey" ] ; then
    RC=3
    msg="$0: parameter missing"
    echo -e "${status[$RC]}: $msg"
    exit $RC
fi

: ${meraki_url=https://n121.meraki.com/}

#
# Get Network-ID of switch
#
curl_response=$( curl -s $meraki_url/api/v1/devices/$serial \
    -H 'Content-Type: application/json' \
    -H 'Accept: application/json' \
    -H "X-Cisco-Meraki-API-Key: $apikey" )
network=$( echo "$curl_response" | jq -r ".networkId" 2> /dev/null )
jq_rc=$?
if [ $jq_rc -eq 0 ] ; then
    case $network in 
        "") 
            exit_status 3 "Empty networkID. Prabably SN '$serial' does not exist"
            ;;
     'null')
            exit_status 3 'No networkID tag found. Wrong api-key?'
            ;;
    esac
else
    exit_status 3 'could not parse curl response' "$curl_response"
fi

#
# Get Alets for this switch
#
filter='.'
response=$( curl -s $meraki_url/api/v1/networks/$network/health/alerts \
    -H 'Content-Type: application/json' \
    -H 'Accept: application/json' \
    -H "X-Cisco-Meraki-API-Key: $apikey"  \
    | jq -r "$filter"
    )
jq_rc=$?

# No alerts at all? Good!
if [ $jq_rc -eq 0 -a "$response" == '[]' ] ; then
    exit_status 0 'No alerts found'
# Alerts, but for our device/serial?
else
    # Select only elements with our device in devices array
    device_filter="select(.[].scope.devices[].serial == \"$serial\")"
    device_errors=$( echo "$response" | jq "$device_filter" )
    if [ -n "$device_errors" ] ;then
        alert_formater='.[] | "Category: \"" + .category + "\" | Type: \"" + .type + "\" | Severity: \"" + .severity + "\""'
        formated=$( echo "$device_errors" | jq -r  "$alert_formater" )
        exit_status 1 'Alerts found' "$formated"

    else
        exit_status 0 'No alerts found'
    fi
fi

