#!/usr/bin/env bash

OPTERR=1
while getopts "s:k:m:" OPTION ; do
    case "$OPTION" in
    s)  serial="$OPTARG"    ;;
    k)  apikey="$OPTARG"    ;;
    m)  meraki_url="$OPTARG" ;;
    ?)   exit 3 ;;
    esac
done

exit_status () {
    local rc=$1
    local msg=$2
    local data=$3

    local status[0]='[OK]'
    local status[1]='[WARNING]'
    local status[2]='[CRITICAL]'
    local status[3]='[UNKNOWN]'

    echo -e "${status[$rc]}: $msg"
    if [ -n "$data" ] ; then
        echo -e "\n\n$data"
    fi
    exit $rc
}

if [ -z "$serial" -o -z "$apikey" ] ; then
    exit_status 3 $msg
fi

: ${meraki_url=https://n121.meraki.com/}
filter='.'

response=$( curl -s $meraki_url/api/v1/devices/$serial \
    -H "X-Cisco-Meraki-API-Key: $apikey"  \
    | jq -r "$filter"
    )
jq_rc=$?

if [ $jq_rc -eq 0 -a -z "$response" ] ; then
    RC=3
    msg="empty response; most likely the device with serial $serial does not exist"
else
    case $jq_rc in
        0)  exit_status 0 'Successfully retrieved device information' "$response"
            ;;
        4)
            exit_status 3 'json parse error; something went wrong. Device does not exist?'
            ;;
        *) 
            exit_status 3 'unknown error code $jq_rc'
            ;;
    esac
fi

