#!/usr/bin/env python3
#
# Check Dell Powervault via API
#
program_version=str(0.3)
# Version 0.3 
#	- write token only after successful login
# Version 0.2 
#	- handling token and (failed) logins
#	- mode 'sysinfo'
#	- experimental modes 'diskgroups', 'volumes'
# Version 0.1 - initial test
#

import requests, json
import os, sys
import argparse
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
from lib.generic_plugin import *
from pathlib import Path

requests.urllib3.disable_warnings()
# parse command line parameters
cli = argparse.ArgumentParser \
	(description='Maintain Aruba Central token')

cli.add_argument('--hostname', '-H', required = True,
		help='IP or FQDN' )
cli.add_argument('--user', '-u', required = True,
		help='XML API User')
cli.add_argument('--password', '-p', required = True,
		help='XML API Password')
cli.add_argument('--mode', '-m', required = True,
		choices=['sysinfo', 'volumes', 'sensors', 'diskgroup' ],
		help='choose which check to perform' )
cli.add_argument('--token', 
		help='use this token instead of getting a new one' )
cli.add_argument('--cachedir', 
		help='path to token cache file', default='/var/spool/icinga2/tmp' )
cli.add_argument('--jsonfile', 
	help='read xml response from file (for debugging)' )
cli.add_argument('--warn', '-w', type=int, help='warning threshold' )
cli.add_argument('--crit', '-c', type=int, help='critical threshold' )
cli.add_argument('-d', '--debug',
		help='enable debugging output', action="store_true")
cli.add_argument('--version',
		action='version', version='%(prog)s ' + program_version)
args = cli.parse_args()

DEBUG=args.debug
import pprint
pp=pprint.PrettyPrinter(indent=4)


#-----------------------------------------------------------------------
# Functions
#-----------------------------------------------------------------------
def check_login(host,user,passwd,token,tokenFilePath,port=False):

	# read from file if no token on CLI
	if not token:
		if DEBUG: print('-------- reading token -------')
		fh = Path(tokenFilePath)
		try:
			token=fh.read_text()
		except:
			if DEBUG: print(f'-------- error reading token from file -----')
			token = login(host,user,passwd,port=False)

		if DEBUG: print(f'-------- token from file: "{token}"')

	# test the token -- either from file or CLI
	if token:
		if DEBUG: print('-------- checking token -------')
		(jr, error) = request( host, token, 'whoami', port=False )

		if DEBUG: pp.pprint( jr )
		if jr.get('status')[0].get('return-code') != 0:
			if DEBUG: print('-------- logging in -------')
			token = login(host,user,passwd,port=False)
			# Write token to cache
			try:
				fh.write_text(token)
			except:
				if DEBUG: print('-------- writing token file -------')
				print( plugin_output(3, 'Unable to write token file!', None, None) )
				sys.exit(3)

				if DEBUG: print('-------- token ok -------')
	# login and get token
	else:
		token = login(host,user,passwd,port=False)

	if DEBUG: print(f'-------- current token: "{token}"')
	return token

def login(host,user,passwd,port=False):
	if port:
		host = f'{host}:{port}'
	url_login = f'https://{host}/api/login'

	header = { 'dataType': 'json' }
	resp = requests.get( url_login, verify=False, 
					 auth=( user, passwd ), headers=header )

	pp.pprint(resp.json())
	if resp != None and resp.headers.get('Content-Type', '').find('application/json')> -1:

		# Answer is login OK?
		api_status = resp.json().get('status')[0].get('return-code')
		if api_status != 1:
			print( plugin_output(3, 'Unable to login!', None, None) )
			sys.exit(3)
		else:
			result = resp.json()

	else:
		error = resp.text

	token = result.get('status')[0].get('response')

	return token

def request(host, token, function, port=False):
	result = None
	error  = None
	if port:
		host = f'{host}:{port}'

	header = { 'dataType': 'json', 'sessionKey': token }

	url_func = f'https://{host}/api/{function}'

	resp = requests.get( url_func, verify=False, headers=header )

	if resp != None and (
			'application/json' in resp.headers.get('Content-Type', '')
			):
		result = resp.json()
	else:
		error = resp.text

	return(result, error)

#-----------------------------------------------------------------------
#								  MAIN
#-----------------------------------------------------------------------

# init vars?
rcode=0;out_text='';detail='';perfdata=''

if DEBUG:
	import pprint
	pp=pprint.PrettyPrinter(indent=4)

# Token file(name) and login
tokenFilePath = args.cachedir + '/' + args.hostname + '.token'
token = check_login( args.hostname, args.user, args.password, args.token, tokenFilePath)

if args.mode == 'diskgroups':
	# Check token

	(jr, error) = request( args.hostname, token, 'show/disk-groups' )

	keys = [ 'name', 'health', 'health-numeric', 'raw-size',
		'blocksize', 'freespace', 'freespace-numeric', 'pool',
		'pool-percentage', 'size', 'size-numeric',
		 'freespace', 'freespace-numeric' 
		 ]
	for diskgroup in jr.get('disk-groups'):
		for key in keys:
			value = diskgroup[key]
			detail += f"{key}:  {value}\n"
		detail += "\n"



elif args.mode == 'sensors':
	# Check token

	(jr, error) = request( args.hostname, token, 'show/sensor-status' )

	infos = {
		'container':	'Container',
		'sensor-name':	'Name',
		'sensor-type':	'Type',
		'status':		'Status',
		'value':		'Value'
		}

	for sensor in jr.get('sensors'):
		for item in infos.keys():
			label = infos[item] + ':'
			value = sensor.get( item )
			detail += f'{label:15}\t{value}\n'

elif args.mode == 'volumes':
	# Check token

	(jr, error) = request( args.hostname, token, 'show/volumes' )

elif args.mode == 'sysinfo':
	# Login
	# Check token
	
	# jr == JSON Response
	(jr, error) = request( args.hostname, token, 'show/system' )

	infos = {
		'vendor-name': 'Vendor',
		'system-information': 'Info',
		'system-name': 'Name',
		'midplane-serial-number': 'Midplane S/N',
		'current-node-wwn': 'Node WWN',
		'system-location': 'Location',
		'system-contact': 'Contact'
		}

	for item in infos.keys():
		label = infos[item] + ':'
		value = jr.get('system')[0].get( item )
		detail += f'{label:15}\t{value}\n'

	out_addition = jr.get('system')[0].get( 'system-name' ) 
	out_text = f"System Info for '{out_addition}"

else:
	rcode=3
	out_text='Unknown value for "--mode": {}'.format( args.mode ) 

if DEBUG:
	if jr:
		print('----------- JSON Response ---------------')
		pp.pprint(jr)
	if error:
		print('----------- Request Error ---------------')
		pp.pprint(error)

print( plugin_output(rcode, out_text, detail, perfdata) )
sys.exit(rcode)

# vim: ts=4:noexpandtab:sw=4:sts=4:ai:smartindent:filetype=python:nofoldenable
