#!/bin/sh
# This script is meant to be used in combination with 'passive_bsdupdates'
# Run this script from cron once a day as root
#
# 2022-04-21 - v1.0 by Xin Qu

result=3

/usr/sbin/freebsd-update updatesready 2>&1 >/dev/null
result=$?

if [ $result -eq 2 ] ; then
	status=OK
elif [ $result -eq 0 ] ; then
	status=WARNING
else
	status=UNKNOWN
fi

echo $status > /var/tmp/chk_psv_bsdupdates

