#!/bin/sh
#
# Check if the installed OS version matches the running kernel version
#
# 2025-09-03 - v1.1 added userland version
# 2021-11-07 - v1.0 by Xin Qu

installed=`freebsd-version -k`
running=`freebsd-version -r`
userland=`freebsd-version -u`

msg_start="Running: $running | Installed: $installed | Userland: $userland"

if [ "$installed" == "$running" ] ; then
    echo -e "(OK): $msg_start"
    exit 0
else
    echo -e "(WARNING): $msg_start"

    echo -e "\nRunning and installed kernel version differ, consider reboot."
    exit 1
fi

