#!/bin/sh
#
# This check only works in combination with 'freebsd_updatesready', what
# does the 'active' part as root. 'freebsd_updatesready' creates the file,
# which is then interpreted by this check script.
# 
# 2022-04-21 - v1.0 by Xin Qu

crf=/var/tmp/chk_psv_bsdupdates
maxage=7

if test `find $crf -mtime -$maxage 2>/dev/null`  ; then
    if test `grep OK $crf` ; then
        state=OK ; ecode=0
        msg='updates were fetched and no updates to install' 
    elif [ `grep WARNING $crf` ] ; then
        state=WARNING ; ecode=1
        msg='there are system updates ready to install'
    else
        state=UNKNOWN ; ecode=3
        msg="can not interpret content of $crf, pls. check manually"
    fi
else 
    state=UNKNOWN
    ecode=3
    msg="check result file '$crf' does not exist or is older than $maxage days"
fi

echo "($state) $msg"
exit $ecode
