#!/usr/bin/env bash
#
# Collects network interface statistics using 'netstat' on FreeBSD. Requires 'jq'.
# 

#
# Process input
#
iface_nameaddress=$1

if [ -z "$iface_nameaddress" ] ; then 
    cat << -EOT
    Interface name required!

    Note that you also *must* specify the IP-Address if the interface
    has multiple IP-Addresses

        <interface-name>[:<ip-address>]

    On a single address interface, it is recommended to ommit the [:<ip-address>]-Part.
    A wrong IP-Address leads to missing Layer 3 statistics.

-EOT
exit 3 ; fi

iface_part=( $(echo $iface_nameaddress | tr ':' ' ') )
iface_name=${iface_part[0]}
iface_addr=${iface_part[1]}

# Select default filter (any ip) or filter by address
if [ -z "$iface_addr" ]  ; then 
	iface_filter='test("Link")|not' 
else
	iface_filter="test(\"$iface_addr\")"
fi

#
# JQ script definitions
#
script_name='.statistics.interface[] | select ( .network | test("Link") ) | .name '
script_ll_address='.statistics.interface[] | select ( .network | test("Link") ) | .address '
script_il_address=".statistics.interface[] | select ( .address | $iface_filter ) | .address "

script_linklayer='.statistics.interface[] | select ( .network | test("Link") ) |
   "eth_recvd-pks=\(."received-packets");
    eth_recvd-errs=\(."received-errors");
    eth_recvd-bytes=\(."received-bytes");
    eth_sent-pks=\(."sent-packets");
    eth_send-errs=\(."send-errors");
    eth_sent-bytes=\(."sent-bytes");
    eth_dropped-pks=\(."dropped-packets");
    eth_colls=\(."collisions"); "
    '
script_iplayer=".statistics.interface[] | select ( .address | $iface_filter ) |
   \"ip_recvd-pks=\(.\"received-packets\");
    ip_recvd-bytes=\(.\"received-bytes\");
    ip_sent-pks=\(.\"sent-packets\");
    ip_sent-bytes=\(.\"sent-bytes\");\"
    "

# 
# Main
#
netstat_out=$( netstat -nb -I $iface_name --libxo=json 2>/dev/null )
nscode=$?

# Check if interface was found. There's no exit code,
# so we have to count the bytes :-(
netstat_length=$( echo $netstat_out | wc -c)


if [ $nscode -ne 0 ] ; then
    state=UNKNOWN
    echo "($state): Interface Perfdata: command 'netstat' returned error"
    exit 3
elif [ "$netstat_length" -lt 40 ] ; then
    state=UNKNOWN
    echo "($state): No data! Probably wrong interface name '$iface_name'"?
    exit 3
else
    state=OK
    if_name=$( echo $netstat_out | jq -r "$script_name" )
    ll_addr=$( echo $netstat_out | jq -r "$script_ll_address" )
    il_addr=$( echo $netstat_out | jq -r "$script_il_address" )
    ll_perf=$( echo $netstat_out | jq -r "$script_linklayer" )
    il_perf=$( echo $netstat_out | jq -r "$script_iplayer" )
    echo "($state): Interface Perfdata of '$if_name'. MAC: $ll_addr, IP: $il_addr |" $ll_perf $il_perf
fi

