#!/usr/bin/env bash

# This plugin checks aruba clearpass radius appliance / server
#
# Author: Xin Qu
#
# Version: 0.2 2025-03-12
#   - check for radius auth failures
#   - check for request evaluation times
#
# Version: 0.1 2024-11-29
#	First test version
#
#

# Define Vars
declare -A snmpData
declare -A snmpUnit
declare -A id
declare -A nameMap

glob_rcode=0

#
# CLI Parsing
#

OPTERR=1
while getopts "H:C:u:x:X:a:A:l:w:c:m:f:F:t:Bhd" OPTION ; do
	case "${OPTION}" in
		H) hostname=${OPTARG}		;;
		C) community="-c ${OPTARG}" ;;
		u) authuser="-u ${OPTARG}"	;;
		a) authproto="-a ${OPTARG}" ;;
		A) authpass="-A ${OPTARG}"	;;
		x) privproto="-x ${OPTARG}" ;;
		X) privpass="-X ${OPTARG}"	;;
		l) seclevel="-l ${OPTARG}"	;;
		w) warn=${OPTARG}			;;
		c) crit=${OPTARG}			;;
		m) mode=${OPTARG}			;;
		f) filter=${OPTARG}			;;
		F) neg_filter=${OPTARG}		;;
		t) tout=${OPTARG}			;;
		B) nobulk=1					;;
		h) helpme=1					;;
		d) debug=1					;;
	esac
done

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Load library functions
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

callpath="$(dirname "$0")"
libdir="${callpath}/../lib"

source $libdir/generic_plugin.shlib
source $libdir/generic_snmp.shlib
source $libdir/convert_and_calc.shlib

#######
# Functions
#######

#
# MAIN
#

#
# set default values
#
mode=${mode:=radius}
filter=${filter:=.}
tout=${tout:=20}
seclevel=${seclevel:=-l authPriv}

check_snmp_args
check_threshold_args

function check_radius_requests {
	local radServerCount='5.0'
	local radServerFailure='4.0'
	local radServerSuccess='3.0'
	#local warn
	#local crit

	total=${snmpData[$baseOID.$radServerCount]}
	failed=${snmpData[$baseOID.$radServerFailure]}
	success=${snmpData[$baseOID.$radServerSuccess]}

	glob_rcode=0
	outmsg+="Radius Global Requests Counter: total: $total, success: $success, failed: $failed"
	perfdata="radReqFailed=$failed;$warn;$crit;0;$total"
}

function check_request_time {
	local radPolicyEvalTime='1.0'
	local radAuthRequestTime='2.0'
	#local warn
	#local crit

	evalTime=${snmpData[$baseOID.$radPolicyEvalTime]}
	requestTime=${snmpData[$baseOID.$radAuthRequestTime]}

	glob_rcode=0
	outmsg+="Radius Policy Perfomance: Evaluation Time: ${evalTime}ms, Total Time: ${requestTime}ms"
	perfdata="radPolicyEvalTime=$evalTime;$warn;$crit "
	perfdata+="radAuthRequestTime=$requestTime;$warn;$crit"
}

case $mode in
	radius)
		baseOID='.1.3.6.1.4.1.14823.1.6.1.1.2.1.1'
		get_snmp_lib
		check_radius_requests
	;;

	evaltime)
		baseOID='.1.3.6.1.4.1.14823.1.6.1.1.2.1.1'
		get_snmp_lib
		check_request_time
	;;

	radiusauth)
		baseOID='.1.3.6.1.4.1.14823.1.6.1.1.2.2.1'
		id[index]=1
		id[name]=2
		#get_snmp_lib_nounit
		get_snmp_lib nounit
		process_snmp_index
		#get_snmp_and_process
	;;
	policy)
		baseOID='.1.3.6.1.4.1.14823.1.6.1.1.2.3.1'
		get_snmp_lib
	;;
	policyproto)
		baseOID='.1.3.6.1.4.1.14823.1.6.1.1.2.4.1'
		get_snmp_lib
	;;
	policyautz)
		baseOID='.1.3.6.1.4.1.14823.1.6.1.1.2.5.1'
		get_snmp_lib
	;;
	webauth)
		baseOID='.1.3.6.1.4.1.14823.1.6.1.1.2.5.1'
		get_snmp_lib
	;;
	
	*)
		echo "(UNKNOWN): mode '-m $mode' not known" ; exit 3 ;;
esac


#
# Tell monitoring system what we found out
#
trigger_exit
