#!/usr/bin/env bash

# Display SNMP system info for various systems
#
# Version: 1.0 2025-09-05 
#   Add synology nas
#
# Version: 0.1 2024-11-04
#   first test version
#

# Define Vars
declare -A snmpData
declare -A id
declare -A nameMap
declare -a elementList

glob_rcode=0

#
# CLI Parsing
#

OPTERR=1
while getopts "H:C:u:x:X:a:A:l:w:c:m:f:F:t:Bhd" OPTION ; do
    case "${OPTION}" in
        H) hostname=${OPTARG}       ;;
        C) community="-c ${OPTARG}" ;;
        u) authuser="-u ${OPTARG}"  ;;
        a) authproto="-a ${OPTARG}" ;;
        A) authpass="-A ${OPTARG}"  ;;
        x) privproto="-x ${OPTARG}" ;;
        X) privpass="-X ${OPTARG}"  ;;
        l) seclevel="-l ${OPTARG}"  ;;
        m) mode=${OPTARG}           ;;
        t) tout=${OPTARG}           ;;
        B) nobulk=1                 ;;
        h) helpme=1                 ;;
        d) debug=1                  ;;
    esac
done

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Load library functions
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

callpath="$(dirname "$0")"
libdir="${callpath}/../lib"

source $libdir/generic_plugin.shlib
source $libdir/generic_snmp.shlib

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Local functions
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

#
# MAIN
#

#
# set default values
#
mode=${mode:=aruba_clearpass_metal}
tout=${tout:=20}
seclevel=${seclevel:=-l authPriv}

check_snmp_args

function system_info {
	local index
	for index in ${!id[@]} ; do
		details+=$( printf "%12s: %s" "${nameMap[$index]}" "${snmpData[$baseOID.${id[$index]}]}" )
		details+="\n"
		if [ "${nameMap[$index]}" == 'Hostname' ] ;then
			snmpHostname="${snmpData[$baseOID.${id[$index]}]}"
		fi

	#Create main plugin output, dependend on a "Hostname" in SNMP
	if [ "$snmpHostname" ] ; then
		outmsg="System Info for $snmpHostname"
	else
		outmsg="System Info for $hostname"
	fi
	done
}

case $mode in
    aruba_clearpass_appliance)
        baseOID='.1.3.6.1.4.1.14823.1.6.1.1.1.1.1'
        get_snmp_lib

		nameMap[4]=Hostname
		nameMap[3]=Version
		nameMap[2]=Model
		nameMap[1]=Type
		nameMap[0]='#Nodes'

		id[4]=4.0
		id[3]=3.0
		id[2]=1.0
		id[1]=5.0
		id[0]=7.0
		system_info
    ;;
    aruba_clearpass_metal)
        baseOID='.1.3.6.1.4.1.14823.1.6.1.1.1.1.1'
        get_snmp_lib
		nameMap[5]=Hostname
		nameMap[4]=Version
		nameMap[3]=Model
		nameMap[2]=Type
		nameMap[1]=S/N
		nameMap[0]='#Nodes'

		id[5]=4.0
		id[4]=3.0
		id[3]=1.0
		id[2]=5.0
		id[1]=2.0
		id[0]=7.0
		system_info
	;;
	synology_nas)
		# Information is on different locations
		mib_nas='1.3.6.1.4.1.6574.1.5'
		mib_gen='1.3.6.1.2.1.1'
		baseOID=".$mib_nas"
		get_snmp_lib nounits
		baseOID=."$mib_gen"
		get_snmp_lib nounits

		# Information is on different locations; do not use baseOID
		# for creating output
		baseOID=''

		nameMap[5]=Hostname
		nameMap[4]=Location
		nameMap[3]=Contact
		nameMap[2]=Version
		nameMap[1]=Model
		nameMap[0]=S/N

		id[5]=${mib_gen}.5.0
		id[4]=${mib_gen}.6.0
		id[3]=${mib_gen}.4.0
		id[2]=${mib_nas}.3.0
		id[1]=${mib_nas}.1.0
		id[0]=${mib_nas}.2.0
		system_info
	;;

    *)
        echo "(UNKNOWN): mode '-m $mode' not known" ; exit 3 ;;
esac


trigger_exit

#
# Tell monitoring system what we found out
#


#vim: set ts=4 noexpandtab sw=4
