#!/usr/bin/env bash

# This plugin checks the fan status of various device types
#
# Author: Xin Qu
#
# Version: 1.0 2024-12-16
#	Support for aruba cx
#	A lot of enhancements
#
# Version: 0.1 2024-03-09
#	First test version
#
#

# Define Vars
declare -A snmpData
declare -A snmpUnit
declare -A id
declare -A nameMap

glob_rcode=0

#
# CLI Parsing
#

OPTERR=1
while getopts "H:C:u:x:X:a:A:l:w:c:m:f:F:t:Bhd" OPTION ; do
	case "${OPTION}" in
		H) hostname=${OPTARG}		;;
		C) community="-c ${OPTARG}" ;;
		u) authuser="-u ${OPTARG}"	;;
		a) authproto="-a ${OPTARG}" ;;
		A) authpass="-A ${OPTARG}"	;;
		x) privproto="-x ${OPTARG}" ;;
		X) privpass="-X ${OPTARG}"	;;
		l) seclevel="-l ${OPTARG}"	;;
		w) warn=${OPTARG}			;;
		c) crit=${OPTARG}			;;
		m) mode=${OPTARG}			;;
		f) filter=${OPTARG}			;;
		F) neg_filter=${OPTARG}		;;
		t) tout=${OPTARG}			;;
		B) nobulk=1					;;
		h) helpme=1					;;
		d) debug=1					;;
	esac
done

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Load library functions
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

callpath="$(dirname "$0")"
libdir="${callpath}/../lib"

source $libdir/generic_plugin.shlib
source $libdir/generic_snmp.shlib
source $libdir/convert_and_calc.shlib

#######
# Functions
#######

function status_stringmap_arubacx {
	local numState=$1

	local -a map
	map[1]='unknown'
	map[2]='tray empty'
	map[3]='uninitialized'
	map[4]='ok'
	map[5]='fault'

	echo "${map[$numState]}"
}

function status_errormap_arubacx {
	local numState=$1

	local -a map
	map[1]=3
	map[2]=0
	map[3]=1
	map[4]=0
	map[5]=2

	echo "${map[$numState]}"
}

function fan_table {
	local filter=$1

	outmsg='Fan Check: '
	for eName in "${!nameMap[@]}"
    do
        if [[  "$eName" =~ $filter ]]
        then
			outElements+=(${nameMap[$eName]})
        fi
    done

	local name
	local speed
	local fanstate
	local fanstate_string
	local detail_line
	local state_byspeed=0
	local state_bystatus=0

    for element in  ${outElements[@]}
    do
        name="${snmpData[${baseOID}.${id[name]}.$element]} ${snmpUnit[${baseOID}.${id[name]}.$element]}"
		# remove quotes
		name=${name//\"/}
		# quick and dirty fix: remove trailing space (real fix above, but requires qnap testing)
		name=${name/% /}

		outmsg+="$name:"
		detail_line="$name:"
		if [ -n "${id[speed]}" ] ; then
			speed=${snmpData[${baseOID}.${id[speed]}.$element]}
			if [ -n "$crit" -a -n "$warn" ] ; then
				state_byspeed=$( calc_state $speed $warn $crit 'low' )
			fi
			state_detail_string=$( state_string $state_byspeed )
			outmsg+=" $speed RPM"
			detail_line+=$( printf "%5d RPM" $speed)
		fi

		if [ -n "${id[state]}" ] ; then
			fanstate=${snmpData[${baseOID}.${id[state]}.$element]}
			fanstate_string=$( status_stringmap_$mode $fanstate )
			state_bystatus=$( status_errormap_$mode $fanstate )
			state_detail_string=$( state_string $state_bystatus )
			#outmsg+=", State: $state_detail_string"
			detail_line+=", State: $fanstate_string"
		fi

		# prefer systems status calculation over speed thresholds
		if [ -n "${id[state]}" ] ; then
			state_detail_string=$( state_string $state_bystatus )
			glob_rcode=$( set_globalstate $state_bystatus )
		else
			state_detail_string=$( state_string $state_byspeed )
			glob_rcode=$( set_globalstate $state_byspeed )
		fi
		detail_line="$state_detail_string $detail_line"

		# merge everything together
		outmsg+="; "
		details+="$detail_line\n"
		perfdata+="$name=$speed;$warn;$crit "
	done
}

function test_errors {
	local prefix=$1
	local object=$2

	outmsg="$prefix"
	case ${snmpData[err]} in
		nosuchobject)
			outmsg+="Device does not have any $object."
			glob_rcode=0
			trigger_exit
			;;
	esac
}

#
# MAIN
#

#
# set default values
#
mode=${mode:=qnap}
filter=${filter:=.}
tout=${tout:=20}

check_snmp_args
check_threshold_args

case $mode in
	qnap)
		baseOID='.1.3.6.1.4.1.55062.1.12.9.1'
		id[index]=1
		id[name]=2
		id[speed]=3
		get_snmp_and_process
		fan_table .
	;;
	arubacx)
		baseOID='.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1'
		id[name]=4
		id[speed]=8
		id[state]=10
		get_snmp_lib
		test_errors 'Fans: ' 'fans'
		process_snmp_namedindex_flex
		fan_table .
	;;
	*)
		echo "(UNKNOWN): mode '-m $mode' not known" ; exit 3 ;;
esac


#
# Tell monitoring system what we found out
#
trigger_exit
