#!/usr/bin/env bash

# General purpose uptime checker, with human readable output
#
# Author: msander
#
# Version: 0.1  2023-04-04
#   first test version
#

# Define Vars
declare -A snmpData
declare -A id
declare -A nameMap
declare -a elementList

glob_rcode=0

#
# CLI Parsing
#

OPTERR=1
while getopts "H:C:u:x:X:a:A:l:w:c:m:f:F:t:Bhd" OPTION ; do
    case "${OPTION}" in
        H) hostname=${OPTARG}       ;;
        C) community="-c ${OPTARG}" ;;
        u) authuser="-u ${OPTARG}"  ;;
        a) authproto="-a ${OPTARG}" ;;
        A) authpass="-A ${OPTARG}"  ;;
        x) privproto="-x ${OPTARG}" ;;
        X) privpass="-X ${OPTARG}"  ;;
        l) seclevel="-l ${OPTARG}"  ;;
        w) warn=${OPTARG}           ;;
        c) crit=${OPTARG}           ;;
        m) mode=${OPTARG}           ;;
        t) tout=${OPTARG}           ;;
        B) nobulk=1                 ;;
        h) helpme=1                 ;;
        d) debug=1                  ;;
    esac
done

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Load library functions
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

callpath="$(dirname "$0")"
libdir="${callpath}/../lib"

source $libdir/generic_plugin.shlib
source $libdir/generic_snmp.shlib
source $libdir/convert_and_calc.shlib

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Local functions
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

function get_snmp {
    #
    # Compose snmp command
    #
    if [ "$nobulk" ]; then walk=snmpwalk;  else walk=snmpbulkwalk; fi
    if [ -n "$authuser" ]; then snmpv=3; else snmpv=2c; fi

    snmpcmd="$walk -Onqt -v $snmpv -t $tout -r 3 \
        $community $authuser $privproto $privpass $seclevel $authproto $authpass \
        $hostname  $baseOID"

    dbg_msg "debug snmpcmd: $snmpcmd"


    # First of all, get the SNMP-Data
    snmpResponse=$($snmpcmd 2>&1)
    snmpexit=$?

    dbg_msg "debugsnmpresponse: $snmpResponse"

    if [ $snmpexit -ne 0 ] ; then
        echo "(UNKNOWN): Problem fetching SNMP data."
        echo 
        echo "SNMP Output was: $snmpResponse"
        exit 3
    fi

    while read oid value
    do 
        snmpData[$oid]="$value"
    done <<< "$snmpResponse"
}

function check_uptime {
    uptime_sec=${snmpData[$baseOID]}
    # Convert 'timeticks' to 'seconds'
    uptime_sec=$(( uptime_sec / 100 ))
    outmsg="Uptime `second_to_hr $uptime_sec`"
    perfdata="uptime_sec=${uptime_sec}s"
}

#
# MAIN
#

#
# set default values
#
mode=${mode:=snmpv2}
tout=${tout:=20}

check_arguments
# 
# precission calculator 'bc' compat. check
#
if [ -x /usr/local/bin/bc ]; then 
    bc=/usr/local/bin/bc
elif [ -x /usr/bin/bc ] ; then
    bc=/usr/bin/bc
fi

case $mode in
    snmpv2)
        baseOID='.1.3.6.1.2.1.1.3.0'
        get_snmp
        check_uptime
    ;;

    hrsystem)
        baseOID='.1.3.6.1.2.1.25.1.1.0'
        get_snmp
        check_uptime
    ;;

    sophosxg)
        baseOID='.1.3.6.1.4.1.2604.5.1.2.2.0'
        get_snmp
        check_uptime
    ;;

    # NAS-MIB: systemUptime
    nas)
        baseOID='.1.3.6.1.4.1.24681.1.2.4.0'
        get_snmp
        check_uptime
    ;;

    # QTS-MIB: sysUptime
    qts)
        baseOID='.1.3.6.1.4.1.55062.1.12.21.0'
        get_snmp
        check_uptime
    ;;

    # NAS-MIB: systemUptimeEX
    nasex)
        baseOID='.1.3.6.1.4.1.24681.1.3.4.0'
        get_snmp
        check_uptime
    ;;
    *)
        echo "(UNKNOWN): mode '-m $mode' not known" ; exit 3 ;;
esac


#
# Tell monitoring system what we found out
#
echo -en "$( state_string $glob_rcode ) $outmsg"
if [ -n "$details" ] ; then echo -en "\n\n$details" ; fi
if [ -n "$perfdata" ] ; then echo -en "|$perfdata" ; fi
echo

exit $glob_rcode


#vim: set ts=4 expandtab sw=4
