#!/usr/bin/env bash

# This plugin checks metrics of a "used / free" type for various devices
#
# Author: Xin Qu
#
# Version: 0.1 2024-11-27
#	First test version
#
#

# Define Vars
declare -A snmpData
declare -A snmpUnit
declare -A id
declare -A nameMap

glob_rcode=0

#
# CLI Parsing
#

OPTERR=1
while getopts "H:C:u:x:X:a:A:l:w:c:m:f:F:t:Bhd" OPTION ; do
	case "${OPTION}" in
		H) hostname=${OPTARG}		;;
		C) community="-c ${OPTARG}" ;;
		u) authuser="-u ${OPTARG}"	;;
		a) authproto="-a ${OPTARG}" ;;
		A) authpass="-A ${OPTARG}"	;;
		x) privproto="-x ${OPTARG}" ;;
		X) privpass="-X ${OPTARG}"	;;
		l) seclevel="-l ${OPTARG}"	;;
		w) warn=${OPTARG}			;;
		c) crit=${OPTARG}			;;
		m) mode=${OPTARG}			;;
		f) filter=${OPTARG}			;;
		F) neg_filter=${OPTARG}		;;
		t) tout=${OPTARG}			;;
		B) nobulk=1					;;
		h) helpme=1					;;
		d) debug=1					;;
	esac
done

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Load library functions
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

callpath="$(dirname "$0")"
libdir="${callpath}/../lib"

source $libdir/generic_plugin.shlib
source $libdir/generic_snmp.shlib
source $libdir/convert_and_calc.shlib

#######
# Functions
#######

function total_free {
	local name="$1"
	# Copy values to handy variables
	local total=${snmpData[${baseOID}.${id[total]}.0]}
	local free=${snmpData[${baseOID}.${id[free]}.0]}
	local used=$(( $total - $free ))
	local relative=$( percent $total $used )

	# Generate human readable sizes
	local total_hr=$( hr_bytes $total )
	local used_hr=$( hr_bytes $used )

	# Update (global) plugin return code
    if [ -n "$warn" -a -n "$crit" ] ;then
        glob_rcode=$( calc_state $relative $warn $crit )
    fi

	# Calculate percentage
	outmsg="$name $used_hr of $total_hr used (${relative}%)"
	perfdata="${relative};$warn;$crit;0;100"
}


#
# MAIN
#

#
# set default values
#
mode=${mode:=mem_arubacppm}
filter=${filter:=.}
tout=${tout:=20}
seclevel=${seclevel:=-l authPriv}

check_snmp_args
check_threshold_args

case $mode in
	mem_arubacppm)
		id[total]=12
		id[free]=13
		baseOID='.1.3.6.1.4.1.14823.1.6.1.1.1.1.1'
		get_snmp_lib
		total_free Memory:
	;;
	disk_arubacppm)
		id[total]=14
		id[free]=15
		baseOID='.1.3.6.1.4.1.14823.1.6.1.1.1.1.1'
		get_snmp_lib
		total_free Disk:
	;;
	
	*)
		echo "(UNKNOWN): mode '-m $mode' not known" ; exit 3 ;;
esac


#
# Tell monitoring system what we found out
#
trigger_exit
